### ISSUE TITLE
images is an array when empty

### ISSUE THREAD

**Issue by aronatkins** [rich-iannone/quarto-email#4]
When there are no images in the output metadata, we have:

```json
{"rsc_email_images":[]}
```

When there are images in the output metadata, we have:

```json
{"rsc_email_images":{"img1.png":"....."}}
```

The value should not be an array when empty. 

It is OK for that value to be an empty map, but other kinds of values are not expected.

**Comment by rich-iannone** [comment]
@aronatkins is it okay to leave `"rsc_email_images"` out of the JSON file entirely if there are no images?

**Comment by aronatkins** [comment]
No fields are required. Totally OK to omit fields when there is no data.
