### ISSUE TITLE
present latest/this version URLs as separate paragraphs

### ISSUE THREAD

**Issue by aronatkins** [rich-iannone/quarto-email#7]
The current presentation of latest/this version

https://github.com/rich-iannone/quarto-email/blob/61443d78e378716819ef8ffc382d798e036c9b48/_extensions/quarto-email/quarto-email.lua#L217-L218

```bash
export RSC_REPORT_RENDERING_URL="[[==RSC_REPORT_RENDERING_URL==]]"
export RSC_REPORT_SUBSCRIPTION_URL="[[==RSC_REPORT_SUBSCRIPTION_URL==]]"
export RSC_REPORT_URL="[[==RSC_REPORT_URL==]]"
quarto render
```

The resulting HTML looks like:

```html
<p>This message was generated on 2023-09-11 10:12:10.</p>

<p>This Version: <a href="[[==RSC_REPORT_RENDERING_URL==]]">[[==RSC_REPORT_RENDERING_URL==]]</a>

Latest Version: <a href="[[==RSC_REPORT_URL==]]">[[==RSC_REPORT_URL==]]</a></p>

<p>If you wish to stop receiving emails for this document, you may <a href="[[==RSC_REPORT_SUBSCRIPTION_URL==]]">unsubscribe here</a>.</p><br/><p>If HTML documents are attached, they may not render correctly when viewed in some email clients. For a better experience, download HTML documents to disk before opening in a web browser.</p>
```

Rendered:

<img width="568" alt="image" src="https://github.com/rich-iannone/quarto-email/assets/362187/eb9abb8b-99b2-4370-9cc6-2efdbe87a285">

The latest and this version URLs should be presented on separate lines, maybe through separate paragraphs or with a `<br>` tag.

<img width="459" alt="image" src="https://github.com/rich-iannone/quarto-email/assets/362187/0be06fb2-f8db-4bbb-969d-a8d13404d674">

Note: These examples are using placeholder values rather than real URLs.

**Comment by aronatkins** [comment]
Here is a layout that used `<br>` rather than `<p>`. Not clear which we should use, here.

<img width="455" alt="image" src="https://github.com/rich-iannone/quarto-email/assets/362187/33d78f50-b591-43a8-9d9f-7fe6af04cfcb">

**Comment by rich-iannone** [comment]
I opted to go with a `"</p>\n\n"` in the Lua code in https://github.com/rich-iannone/quarto-email/commit/25680b452583c58e31ba4c23430ed24016c356ef. It's now cleaned up so each piece of information is on its own line. Here's a partial screenshot from an email sent to myself after the change:

<img width="257" alt="connect_email_footer" src="https://github.com/rich-iannone/quarto-email/assets/5612024/ff97fc90-0757-48b5-b78c-f596250685ba">

We can always tweak this later if this still looks off.
